package test;

public enum SFSErrorCode {
    HANDSHAKE_API_OBSOLETE, LOGIN_BAD_ZONENAME, LOGIN_BAD_USERNAME, LOGIN_BAD_PASSWORD, LOGIN_BANNED_USER, LOGIN_ZONE_FULL, LOGIN_ALREADY_LOGGED, LOGIN_SERVER_FULL, LOGIN_INACTIVE_ZONE, LOGIN_NAME_CONTAINS_BAD_WORDS, LOGIN_GUEST_NOT_ALLOWED, LOGIN_BANNED_IP, ROOM_DUPLICATE_NAME, CREATE_ROOM_BAD_GROUP, ROOM_NAME_BAD_SIZE, ROOM_NAME_CONTAINS_BADWORDS, CREATE_ROOM_ZONE_FULL, CREATE_ROOM_EXCEED_USER_LIMIT, CREATE_ROOM_WRONG_PARAMETER, JOIN_ALREADY_JOINED, JOIN_ROOM_FULL, JOIN_BAD_PASSWORD, JOIN_BAD_ROOM, JOIN_ROOM_LOCKED, SUBSCRIBE_GROUP_ALREADY_SUBSCRIBED, SUBSCRIBE_GROUP_NOT_FOUND, UNSUBSCRIBE_GROUP_NOT_SUBSCRIBED, UNSUBSCRIBE_GROUP_NOT_FOUND, GENERIC_ERROR, ROOM_NAME_CHANGE_PERMISSION_ERR, ROOM_PASS_CHANGE_PERMISSION_ERR, ROOM_CAPACITY_CHANGE_PERMISSION_ERR, SWITCH_NO_PLAYER_SLOTS_AVAILABLE, SWITCH_NO_SPECTATOR_SLOTS_AVAILABLE, SWITCH_NOT_A_GAME_ROOM, SWITCH_NOT_JOINED_IN_ROOM, BUDDY_LIST_LOAD_FAILURE, BUDDY_LIST_FULL, BUDDY_BLOCK_FAILURE, BUDDY_TOO_MANY_VARIABLES, JOIN_GAME_ACCESS_DENIED, JOIN_GAME_NOT_FOUND, INVITATION_NOT_VALID;

    private short id;

    public short getId() {
        return this.id;
    }
    
    public static void main(String[] args) {
//        System.out.println(LOGIN_BAD_ZONENAME.getId());
        double c = 2.0 - 1.1;
        double d = 2.0 - 1.1;
        
        System.out.println(c + d + 0.1);
        System.out.println((2-1.1)+1.1);
    }
}


